### ISSUE TITLE
socket.error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by pep8** [niklasb/dryscrape#10] opened 2012-06-27 16:46 UTC
first, thank you for the opportunity to parse the javascript powered pages )
but I have a problem. some  url crashes my application without exception message.
it just prints 'Killed' and terminated. for example

    >>> sess.at_xpath("id('main')/div/div[2]/div/div[2]/ul/li[2]/a").text()
    'Return to a previous version of Yahoo! Mail'
    >>> sess.at_xpath("id('main')/div/div[2]/div/div[2]/ul/li[2]/a").get_attr('href')
    'http://us.mg6.mail.yahoo.com/neo/optOut?rs=1&ncrumb=EoJFBwCfiHm'
    >>> sess.visit('http://us.mg6.mail.yahoo.com/neo/optOut?rs=1&ncrumb=EoJFBwCfiHm')
    Killed
    ~/#

the same when call `sess.at_xpath("id('main')/div/div[2]/div/div[2]/ul/li[2]/a").click()`

which means 'Killed'?
how to avoid it?

**Comment by carlzoo** [comment] 2015-06-28 03:40
Hello,
I found that this can be caused with starting and closing a new xvfb display.

I tried with this code:
```python
#!/usr/bin/env python
import dryscrape
from xvfbwrapper import Xvfb

vdisplay = Xvfb()
vdisplay.start()

sess = dryscrape.Session(base_url = "http://www.google.com")

sess.visit('/')
sess.at_css('.gb_c', timeout=20) 

vdisplay.stop()

vdisplay.start()

sess.visit('/')
sess.at_css('.gb_c', timeout=20) 
vdisplay.stop()
```

This outputs
```bash
Error: Xvfb did not start
Traceback (most recent call last):
  File "jstest.py", line 17, in <module>
    sess.visit('/')
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/dryscrape/session.py", line 29, in visit
    return self.driver.visit(self.complete_url(url))
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/webkit_server.py", line 230, in visit
    self.conn.issue_command("Visit", url)
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/webkit_server.py", line 450, in issue_command
    self._writeline(str(len(args)))
  File "/home/carl/workspace/env2/lib/python2.7/site-packages/webkit_server.py", line 501, in _writeline
    self._sock.send(line + "\n")
socket.error: [Errno 32] Broken pipe
```
However, if I do not stop vdisplay in between
```python
#!/usr/bin/env python
import dryscrape
from xvfbwrapper import Xvfb

vdisplay = Xvfb()
vdisplay.start()

sess = dryscrape.Session(base_url = "http://www.google.com")

sess.visit('/')
sess.at_css('.gb_c', timeout=20) 

sess.visit('/')
sess.at_css('.gb_c', timeout=20) 
vdisplay.stop()
```
Then everything works fine.
Is this by design or is their a bug?

**Comment by niklasb** [comment] 2015-07-01 11:10
@carlzoo  This is expected behaviour, a necessity of sorts. webkit-server, or rather QtWebKit needs an X11 connection to work. The dryscrape.Session() constructor starts a webkit-server process which connects to the current X server. If you kill that X server in between, it can no longer function.

**Comment by niklasb** [comment] 2015-07-01 11:28
@pep8 Sorry, I cannot reproduce this on the Yahoo page, nor any other. Did you verify that proxychains is not the problem? Closing this issue for now.

**Closed by niklasb** 2015-07-01 11:28 UTC
